name: PR Opened
description: Checks all basic requirements are in place
runs:
  using: node12
  main: action.js
inputs:
  token:
    description: PAT for authorisation
    required: false
    default: ${{ github.token }}
