name: PR Opened

on:
  pull_request:
    types: [opened]
#     branches:
#       - master
    paths:
      - 'widgets/*.html'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Simple Diff
        uses: mudlabs/simple-diff@v1.2.0
        id: diff
      - name: Process
        run: exit 1
        if: steps.diff.outputs.removed == true
      - name: PR Opened
        uses: ./.github/action/pr.yaml
