name: Widgets

on:
  push:
#     branches:
#       - master
    paths:
      - 'widgets/*.html'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
#       - name: Diffy
#         uses: mudlabs/diffy@v1.0.0
#         id: diffy
      - name: Simple Diff
        uses: mudlabs/simple-diff@v1.2.0
        id: diff
      - name: Modify Widgets
        uses: ./.github/action
        with:
          deleted: ${{steps.diff.outputs.removed}}
          added: ${{steps.diff.outputs.added}}
          modified: ${{steps.diff.outputs.modified}}
          renamed: ${{steps.diff.outputs.renamed}}
          name: ${{steps.diff.outputs.name}}
          previous: ${{steps.diff.outputs.previous}}
#       - name: Update Readme
#         uses: ./.github/action
# #         if: success() && (steps.diffy.outputs.removed == true || steps.diffy.outputs.added == true)
#       - name: Add and Commit
#         uses: EndBug/add-and-commit@v5.1.0
#         if: success()
